name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: python_backend
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Use the Python version your project requires

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Export DB_PASSWORD and DB_USERNAME
        run: |
          export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          export DB_USERNAME="${{ secrets.DB_USERNAME }}"
          echo "DB_USER: $DB_USERNAME"
          echo "DB_PASSWORD: $DB_PASSWORD"
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Apply database migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}

